packages:
    - 'homepage'
    - 'directwerk-admin'
    - 'directwerk-docs'
    - 'directwerk-studio'
    - 'directwerk-web'
    - 'packages/*'

ignoredBuiltDependencies:
    - sharp
    - unrs-resolver
