plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}
rootProject.name = 'Directwerk'

include(
        'directwerk-common',
        'directwerk-queue',
        'directwerk-email',
        'directwerk-core',
        'directwerk-subscription',
        'directwerk-digital',
        'directwerk-podcast',
        'directwerk-newsletter',
        'directwerk-app'
)
